Explained physically isolated paths
tsvwg/ietf-multipath-dccp pull request #311
Opened 2024-07-30 11:46 UTC by markusa

Closes #302

2024-07-31 08:44 UTC, gorryfair requested changes
I would saw /path/ rather than /route/

2024-07-31 10:06 UTC, markusa commented on draft-ietf-tsvwg-multipath-dccp.mkd
>  The corresponding control information allows the receiver to optionally
https://github.com/tsvwg/ietf-multipath-dccp/pull/311/commits/424f854631277e8ead86405500d18656949fa475

2024-07-31 11:11 UTC, gorryfair approved these changes

2024-09-11 21:59 UTC, zaheduzzaman approved these changes

2024-09-12 08:08 UTC, merged